"""empty message

Revision ID: 145c8286816e
Revises: 8ebd219a5a4a
Create Date: 2020-07-16 16:02:25.602580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145c8286816e'
down_revision = '8ebd219a5a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
