"""empty message

Revision ID: 290254e35abc
Revises: aabb293d23a4
Create Date: 2020-07-17 21:48:36.004617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290254e35abc'
down_revision = 'aabb293d23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'method')
    # ### end Alembic commands ###
