"""empty message

Revision ID: 466f2c62e5c6
Revises: 57b7081fbdd5
Create Date: 2020-07-17 14:45:20.549297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466f2c62e5c6'
down_revision = '57b7081fbdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
