"""empty message

Revision ID: 4ca255fac6a6
Revises: d5af3558152c
Create Date: 2020-07-18 13:26:37.327087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca255fac6a6'
down_revision = 'd5af3558152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'transaction_date')
    # ### end Alembic commands ###
