"""empty message

Revision ID: 57b7081fbdd5
Revises: a3060b19d397
Create Date: 2020-07-17 14:29:44.372651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b7081fbdd5'
down_revision = 'a3060b19d397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
