"""empty message

Revision ID: 9848d5da73b8
Revises: 6c7eb46a8f8e
Create Date: 2020-07-18 13:05:08.204196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9848d5da73b8'
down_revision = '6c7eb46a8f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'transaction_date')
    # ### end Alembic commands ###
