"""empty message

Revision ID: a3060b19d397
Revises: fe085678f2fb
Create Date: 2020-07-17 14:22:59.660026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3060b19d397'
down_revision = 'fe085678f2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
