"""empty message

Revision ID: aabb293d23a4
Revises: ec2a0313c67b
Create Date: 2020-07-17 19:21:03.642953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabb293d23a4'
down_revision = 'ec2a0313c67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'method')
    # ### end Alembic commands ###
