"""empty message

Revision ID: d411a2dfac65
Revises: 4ca255fac6a6
Create Date: 2020-07-18 13:27:19.594232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd411a2dfac65'
down_revision = '4ca255fac6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_date', sa.DateTime(), server_default='<built-in method utcnow of type object at 0x10fd2f648>', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'transaction_date')
    # ### end Alembic commands ###
