"""empty message

Revision ID: ec2a0313c67b
Revises: ac6375b01129
Create Date: 2020-07-17 19:15:59.612044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2a0313c67b'
down_revision = 'ac6375b01129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('buyer_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'user', ['buyer_user_id'], ['user_id'])
    op.drop_column('payment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['user_id'])
    op.drop_column('payment', 'buyer_user_id')
    # ### end Alembic commands ###
