"""empty message

Revision ID: f05633b0adfd
Revises: 290254e35abc
Create Date: 2020-07-17 22:06:14.081908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05633b0adfd'
down_revision = '290254e35abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', sa.String(), server_default='Knet', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'method')
    # ### end Alembic commands ###
