"""empty message

Revision ID: fe085678f2fb
Revises: 145c8286816e
Create Date: 2020-07-17 14:19:09.008855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe085678f2fb'
down_revision = '145c8286816e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
